version: '3.8'
services:
  mysql-standalone:
    container_name: "mysql-product-service"
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=cs590
      - MYSQL_DATABASE=product
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=cs590
    ports:
      - "3308:3306"




